add node requirements command

diff --git a/oda b/oda
--- a/oda
+++ b/oda
@@ -1102,10 +1102,11 @@ oda_node_usage() {
 	echo
 	# :command.usage_commands
 	printf "%s\n" "Commands:"
-	printf "  %s   mount project and odoo to system\n" "mount  "
-	printf "  %s   Backup database filestore and addons\n" "backup "
-	printf "  %s   install systemd startup script\n" "systemd"
-	printf "  %s   direct rsyslog to logger\n" "logger "
+	printf "  %s   mount project and odoo to system\n" "mount       "
+	printf "  %s   Backup database filestore and addons\n" "backup      "
+	printf "  %s   install requirements to run Odoo (RUN THIS FIRST)\n" "requirements"
+	printf "  %s   install systemd startup script\n" "systemd     "
+	printf "  %s   direct rsyslog to logger\n" "logger      "
 	echo
 
 	# :command.long_usage
@@ -1197,6 +1198,35 @@ oda_node_backup_usage() {
 		# :command.usage_examples
 		printf "%s\n" "Examples:"
 		printf "  oda backup\n"
+		echo
+
+	fi
+}
+
+# :command.usage
+oda_node_requirements_usage() {
+	if [[ -n $long_usage ]]; then
+		printf "oda node requirements - install requirements to run Odoo (RUN THIS FIRST)\n"
+		echo
+
+	else
+		printf "oda node requirements - install requirements to run Odoo (RUN THIS FIRST)\n"
+		echo
+
+	fi
+
+	printf "%s\n" "Usage:"
+	printf "  oda node requirements\n"
+	printf "  oda node requirements --help | -h\n"
+	echo
+
+	# :command.long_usage
+	if [[ -n $long_usage ]]; then
+		printf "%s\n" "Options:"
+
+		# :command.usage_fixed_flags
+		printf "  %s\n" "--help, -h"
+		printf "    Show this help\n"
 		echo
 
 	fi
@@ -2101,6 +2131,9 @@ oda_node_mount_command() {
 	ROPTS="ro,async,noatime"
 	WOPTS="rw,sync,relatime"
 
+	sudo systemctl stop odoo.service
+	sudo mkdir -p ${BASE}/{addons,conf,data,backups,odoo,enterprise}
+
 	cat <<-_EOF_ | tee /tmp/odoo_fstab > /dev/null
 	#BEGINODOO
 	odoofs:${BSHARE} ${BASE}/backups nfs4 ${WOPTS},${COPTS} 0 0
@@ -2123,6 +2156,51 @@ oda_node_backup_command() {
 	# src/node_backup_command.sh
 	BASE=/opt/odoo
 	python3 -B ${BASE}/oda_db.py -b
+}
+
+# :command.function
+oda_node_requirements_command() {
+	# src/node_requirements_command.sh
+	# PostgreSQL Repo
+	sudo wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O /etc/apt/trusted.gpg.d/pgdg.gpg.asc
+	echo 'deb http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main' | sudo tee /etc/apt/sources.list.d/pgdg.list
+
+	# update system
+	sudo bash -c "apt-get update -y && apt-get dist-upgrade -y && apt-get autoremove -y && apt-get autoclean -y"
+
+	# install python and node
+	sudo apt-get install -y --no-install-recommends python3 python3-pip python3-setuptools nodejs npm
+	# install requirements
+	sudo apt-get install -y --no-install-recommends \
+		bzip2 ca-certificates curl dirmngr fonts-liberation fonts-noto fonts-noto-cjk fonts-noto-mono \
+		gnupg gsfonts inetutils-ping libgnutls-dane0 libgts-bin libpaper-utils locales nfs-common \
+		postgresql-client-15 shared-mime-info unzip xz-utils zip \
+		python3-babel python3-chardet python3-cryptography python3-cups python3-dateutil \
+		python3-decorator python3-docutils python3-feedparser python3-freezegun python3-geoip2 \
+		python3-gevent python3-greenlet python3-html2text python3-idna python3-jinja2 \
+		python3-ldap python3-libsass python3-lxml python3-markupsafe python3-num2words \
+		python3-ofxparse python3-olefile python3-openssl python3-paramiko python3-passlib \
+		python3-pdfminer python3-phonenumbers python3-pil python3-polib python3-psutil \
+		python3-psycopg2 python3-pydot python3-pylibdmtx python3-pyparsing python3-pypdf2 \
+		python3-pytzdata python3-qrcode python3-renderpm python3-reportlab python3-reportlab-accel \
+		python3-requests python3-rjsmin python3-serial python3-stdnum python3-urllib3 \
+		python3-usb python3-vobject python3-werkzeug python3-xlrd python3-xlsxwriter \
+		python3-xlwt python3-zeep
+
+	# install wkhtmltopdf
+	wget -q https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_amd64.deb -O wkhtmltox.deb
+	sudo apt-get install -y --no-install-recommends ./wkhtmltox.deb \
+	rm -rf wkhtmltox.deb
+
+	# install additional python libraries
+	sudo pip install --upgrade pip
+	sudo pip3 install ebaysdk google-auth
+
+	# install additional node libraries
+	sudo npm -g i rtlcss
+
+	# mkdir mount directories
+	sudo bash -c "mkdir -p /opt/odoo/{addons,conf,data,backups,odoo,enterprise} && chown odoo:odoo /opt/odoo"
 }
 
 # :command.function
@@ -4085,6 +4163,13 @@ oda_node_parse_requirements() {
 			shift $#
 			;;
 
+		requirements)
+			action="requirements"
+			shift
+			oda_node_requirements_parse_requirements "$@"
+			shift $#
+			;;
+
 		systemd)
 			action="systemd"
 			shift
@@ -4233,6 +4318,50 @@ oda_node_backup_parse_requirements() {
 
 	# :command.command_filter
 	action="node backup"
+
+	# :command.parse_requirements_while
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+
+			-?*)
+				printf "invalid option: %s\n" "$key" >&2
+				exit 1
+				;;
+
+			*)
+				# :command.parse_requirements_case
+				# :command.parse_requirements_case_simple
+				printf "invalid argument: %s\n" "$key" >&2
+				exit 1
+
+				;;
+
+		esac
+	done
+
+}
+
+# :command.parse_requirements
+oda_node_requirements_parse_requirements() {
+	# :command.fixed_flags_filter
+	while [[ $# -gt 0 ]]; do
+		case "${1:-}" in
+			--help | -h)
+				long_usage=yes
+				oda_node_requirements_usage
+				exit
+				;;
+
+			*)
+				break
+				;;
+
+		esac
+	done
+
+	# :command.command_filter
+	action="node requirements"
 
 	# :command.parse_requirements_while
 	while [[ $# -gt 0 ]]; do
@@ -4872,6 +5001,7 @@ run() {
 		"node") oda_node_command ;;
 		"node mount") oda_node_mount_command ;;
 		"node backup") oda_node_backup_command ;;
+		"node requirements") oda_node_requirements_command ;;
 		"node systemd") oda_node_systemd_command ;;
 		"node logger") oda_node_logger_command ;;
 		"fs") oda_fs_command ;;
