add remote to node restore

diff --git a/oda b/oda
--- a/oda
+++ b/oda
@@ -1511,13 +1511,19 @@ oda_node_restore_usage() {
 	fi
 
 	printf "%s\n" "Usage:"
-	printf "  oda node restore FILE...\n"
+	printf "  oda node restore FILE... [OPTIONS]\n"
 	printf "  oda node restore --help | -h\n"
 	echo
 
 	# :command.long_usage
 	if [[ -n $long_usage ]]; then
 		printf "%s\n" "Options:"
+
+		# :command.usage_flags
+		# :flag.usage
+		printf "  %s\n" "--remote"
+		printf "\n"
+		echo
 
 		# :command.usage_fixed_flags
 		printf "  %s\n" "--help, -h"
@@ -2314,7 +2320,7 @@ oda_remote_restore_usage() {
 	fi
 
 	printf "%s\n" "Usage:"
-	printf "  oda remote restore NODE [REMOTEFS] FILE...\n"
+	printf "  oda remote restore NODE FILE...\n"
 	printf "  oda remote restore --help | -h\n"
 	echo
 
@@ -2333,12 +2339,6 @@ oda_remote_restore_usage() {
 		# :argument.usage
 		printf "  %s\n" "NODE"
 		printf "\n"
-		echo
-
-		# :argument.usage
-		printf "  %s\n" "REMOTEFS"
-		printf "\n"
-		printf "    Default: odoofs\n"
 		echo
 
 		# :argument.usage
@@ -3231,11 +3231,12 @@ oda_node_backup_command() {
 # :command.function
 oda_node_restore_command() {
 	# src/node_restore_command.sh
+	[[ -z ${args[--remote]} ]] && REMOTE="" || REMOTE="--remote"
 	BASE=/opt/odoo
 	cd ${BASE}
 	for bfile in ${args[file]}
 	do
-		sudo -u odoo python3 -B /usr/local/bin/oda_db.py -r -d "${bfile}"
+		sudo -u odoo python3 -B /usr/local/bin/oda_db.py ${REMOTE} -r -d "${bfile}"
 	done
 }
 
@@ -3473,21 +3474,22 @@ oda_remote_restore_command() {
 	echo "# you can edit it freely and regenerate (it will not be overwritten)"
 	inspect_args
 
+	REMOTE_FS=odoofs
 	echo ${args[node]}
 	echo ${args[remote]}
 	echo ${args[file]}
 
-	# DUMP_FILE="backups/2023_08_14_04_13_58_Dec30data.tar.zst"
-	# PROJECT=$(ssh ${args[node]} -- cat /etc/fstab | grep addons | awk '{print $1}' | awk -F':' '{print $2}' | sed 's,/addons$,,')
+	PROJECT=$(ssh ${args[node]} -- cat /etc/fstab | grep addons | awk '{print $1}' | awk -F':' '{print $2}' | sed 's,/addons$,,')
+	DB=$(ssh ${args[node]} -- grep db_name /opt/odoo/conf/odoo.conf | sed 's/ //g' | awk -F'=' '{print $2}')
+	# ssh ${REMOTE_FS} -- sudo -u odoo rm -rf ${PROJECT}/data/*
+	# ssh ${REMOTE_FS} -- sudo -u odoo mkdir -p ${PROJECT}/data/filestore/${DB}
+	# ssh ${REMOTE_FS} -- sudo -u odoo tar -axf /share/${args[file]} -C ${PROJECT}/data/filestore/${DB} --strip-components=2 ./filestore
 
-	# restore filestore on odoofs
-	# DUMP_FILE="backups/2023_08_14_04_13_58_Dec30data.tar.zst"
-	# DB="quest15issue_285"
-	# echo sudo -u odoo rm -rf ${PROJECT}/data/*
-	# echo sudo -u odoo mkdir -p ${PROJECT}/data/filestore/${DB}
-	# echo sudo -u odoo tar -axf /share/${DUMP_FILE} -C ${PROJECT}/data/filestore/${DB} --strip-components=2 ./filestore
+	# stop service
+	ssh ${args[node]} -- sudo systemctl stop odoo.service
 
-	# echo ssh ${args[remote]} sudo -u odoo rm -rf ${PROJECT}/data/*
+	# restore db on node
+	ssh ${args[node]} -- 'cd /opt/odoo && pwd && sudo -u odoo python3 -B /usr/local/bin/oda_db.py --remote -r -d ${args[file]}'
 
 	# if [[ -f "./conf/odoo.conf" ]]; then
 	#   BASE=`dirname "${0}"`
@@ -6145,6 +6147,13 @@ oda_node_restore_parse_requirements() {
 	while [[ $# -gt 0 ]]; do
 		key="$1"
 		case "$key" in
+			# :flag.case
+			--remote)
+
+				# :flag.case_no_arg
+				args['--remote']=1
+				shift
+				;;
 
 			-?*)
 				printf "invalid option: %s\n" "$key" >&2
@@ -6170,7 +6179,7 @@ oda_node_restore_parse_requirements() {
 
 	# :command.required_args_filter
 	if [[ -z ${args['file']+x} ]]; then
-		printf "missing required argument: FILE\nusage: oda node restore FILE...\n" >&2
+		printf "missing required argument: FILE\nusage: oda node restore FILE... [OPTIONS]\n" >&2
 		exit 1
 	fi
 
@@ -7609,10 +7618,6 @@ oda_remote_restore_parse_requirements() {
 					args['node']=$1
 					shift
 
-				elif [[ -z ${args['remotefs']+x} ]]; then
-					args['remotefs']=$1
-					shift
-
 				elif [[ -z ${args['file']+x} ]]; then
 					args['file']="\"$1\""
 					shift
@@ -7628,16 +7633,13 @@ oda_remote_restore_parse_requirements() {
 
 	# :command.required_args_filter
 	if [[ -z ${args['node']+x} ]]; then
-		printf "missing required argument: NODE\nusage: oda remote restore NODE [REMOTEFS] FILE...\n" >&2
+		printf "missing required argument: NODE\nusage: oda remote restore NODE FILE...\n" >&2
 		exit 1
 	fi
 	if [[ -z ${args['file']+x} ]]; then
-		printf "missing required argument: FILE\nusage: oda remote restore NODE [REMOTEFS] FILE...\n" >&2
+		printf "missing required argument: FILE\nusage: oda remote restore NODE FILE...\n" >&2
 		exit 1
 	fi
-
-	# :command.default_assignments
-	[[ -n ${args['remotefs']:-} ]] || args['remotefs']="odoofs"
 
 }
 
